name: validate
on: [push, pull_request]
env:
  REMIX_REGISTRY_TOKEN: ${{ secrets.REMIX_REGISTRY_TOKEN }}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: 🚀 Deploy
        # only deploy main branch on pushes
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.6.8
        env:
          # "HD_" is removed by akhileshns/heroku-deploy
          # from the docs:
          # > so the action can tell your environment variable apart
          # > from multiple other variables (passed by your language,
          # > github actions etc) which you probably don't want sitting
          # > in your heroku app's config vars.
          HD_REMIX_REGISTRY_TOKEN: ${{ secrets.REMIX_REGISTRY_TOKEN }}
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: cask-search
          heroku_email: logan@mcan.sh
